const $=s=>document.querySelector(s);
const products=[{id:'phone',name:'Смартфоны',category:'Техника',image:'assets/tech.webp',text:'Концепт раздела смартфонов. Конкретные модели и условия пока не заданы.'},{id:'gaming',name:'Игровые устройства',category:'Техника',image:'assets/gaming.webp',text:'Демонстрационная карточка техники. Реального заказа в этом макете нет.'}];
const fav=new Set();let devices=2,months=1,category='Все',query='';
const safe=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,route)=>`<a class="primary" href="#${route}">${text} →</a>`;
const hero=(title,sub,compact=false)=>`<section class="hero ${compact?'compact':''}"><span class="eyebrow">VAPEBAZAR · 夜</span><h1>${title}</h1><p>${sub}</p></section>`;
const back=title=>`<a class="back" href="#profile">← Профиль</a><h1>${title}</h1>`;
const row=(label,route)=>`<a class="row" href="#${route}"><span>${label}</span><span aria-hidden="true">›</span></a>`;
function card(p){return `<article class="card"><button class="heart" data-fav="${p.id}" aria-label="${fav.has(p.id)?'Убрать из':'Добавить в'} избранное" aria-pressed="${fav.has(p.id)}">${fav.has(p.id)?'♥':'♡'}</button><img src="${p.image}" alt="Иллюстрация категории ${p.name}" loading="lazy"><div class="card-body"><h3>${p.name}</h3><small>Иллюстрация категории</small><button class="outline" data-detail="${p.id}">Подробнее →</button></div></article>`}
const grid=ps=>`<div class="grid">${ps.map(card).join('')}</div>`;
function render(){const page=location.hash.slice(1)||'home';let html='';
if(page==='home')html=hero('Твой<br>Bazar','Японская атмосфера.<br>Техника и сервисы.')+`<p style="margin-top:14px">${button('Открыть каталог','catalog')}</p><section class="panel vpn-card"><span class="symbol">◇</span><div><h3>VapeBazar VPN</h3><p class="muted">Подключение для твоих устройств</p>${button('Выбрать тариф','vpn')}</div></section><h2>Техника и устройства</h2>${grid(products)}<div class="panel rows">${row('Поможем с выбором','support')}</div>`;
else if(page==='catalog')html=hero('Каталог','Техника и устройства',true)+`<label for="search" class="muted">Поиск по каталогу</label><input class="search" id="search" type="search" placeholder="Название категории" value="${safe(query)}"><div class="chips">${['Все','Техника'].map(x=>`<button data-category="${x}" aria-pressed="${x===category}">${x}</button>`).join('')}</div><div id="results"></div><section class="panel"><h3>Визуальные материалы · 18+</h3><p class="muted">Под-системы и жидкости</p><small>Информационные названия разделов. Карточки продажи, цены и заказ отсутствуют.</small></section>`;
else if(page==='vpn')html=hero('Оставайся<br>на связи','Выбери подключение под себя',true)+`<section class="panel"><h3>Количество устройств</h3><div class="chips">${[1,2,3,5].map(n=>`<button data-devices="${n}" aria-pressed="${devices===n}">${n}</button>`).join('')}</div><h3>Срок подключения</h3><div class="chips">${[1,3,6].map(n=>`<button data-months="${n}" aria-pressed="${months===n}">${n} ${n===1?'месяц':n===3?'месяца':'месяцев'}</button>`).join('')}</div><p class="row"><span>Стоимость</span><strong>Не задана</strong></p><button class="primary wide" data-vpn>Посмотреть выбор →</button><p class="muted"><small>Демонстрация выбора. Оплата и выдача доступа не подключены.</small></p></section><div class="panel rows">${row('Как подключиться','guide')}${row('Помощь с настройкой','support')}</div>`;
else if(page==='profile')html=hero('Твой профиль','Демонстрационный аккаунт',true)+`<div class="panel rows">${[['Мои заказы','orders'],['Мой VPN','myvpn'],['Избранное','favorites'],['Бонусы','bonus'],['Настройки','settings'],['Поддержка','support']].map(x=>row(...x)).join('')}</div>`;
else if(page==='favorites')html=back('Избранное')+(fav.size?grid(products.filter(p=>fav.has(p.id))):`<div class="panel empty"><span class="symbol">♡</span><h2>Пока пусто</h2><p class="muted">Сохраняй интересные категории сердечком.</p>${button('Открыть каталог','catalog')}</div>`);
else if(page==='orders')html=back('Мои заказы')+`<div class="panel empty"><span class="symbol">▣</span><h2>Заказов пока нет</h2><p class="muted">Здесь появится история заказов. В макете заказы не создаются.</p>${button('Открыть каталог','catalog')}</div>`;
else if(page==='myvpn')html=back('Мой VPN')+hero('Твой VPN','Всё о подключении — здесь',true)+`<div class="panel empty"><span class="symbol">◇</span><h2>Пока нет подписки</h2><p class="muted">Посмотри варианты подключения.</p>${button('Посмотреть тарифы','vpn')}</div><div class="panel rows">${row('Инструкция','guide')}${row('Помощь','support')}</div>`;
else if(page==='bonus')html=back('Бонусы')+hero('Бонусная<br>программа','Раздел для будущих предложений',true)+`<div class="panel"><h3>Условия ещё не заданы</h3><p class="muted">Баланс и правила появятся после согласования программы.</p>${button('Задать вопрос','support')}</div>`;
else if(page==='settings')html=back('Настройки')+`<section class="panel"><h3>Оформление</h3><label class="row"><span>Светлая тема</span><input id="theme" class="switch" type="checkbox" ${document.body.classList.contains('light')?'checked':''}></label><p class="muted">Настройка действует в этом макете.</p></section><section class="panel"><h3>Уведомления</h3><p class="muted">Уведомления будут доступны после подключения сервиса.</p></section>`;
else if(page==='guide')html=`<a class="back" href="#myvpn">← Мой VPN</a><h1>Как подключиться</h1><div class="panel"><p>1. Выбери количество устройств и срок.</p><p>2. После подключения сервиса получи настройки.</p><p>3. Следуй инструкции для своего устройства.</p><p class="notice">В демонстрации ключи и подписки не выдаются.</p></div>${button('Помощь с настройкой','support')}`;
else if(page==='support')html=back('Поддержка')+`<div class="panel"><h2>Поможем разобраться</h2><p class="muted">Раздел для вопросов о технике и подключении VPN.</p><p class="notice">Чат в макете не подключён. Сообщения никуда не отправляются.</p></div>`;
else{location.hash='home';return;}
$('#screen').innerHTML=html;document.querySelectorAll('nav a').forEach(a=>{const active=a.dataset.tab===(['home','catalog','vpn'].includes(page)?page:'profile');if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(page==='catalog')results();}
function results(){const ps=products.filter(p=>(category==='Все'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase().trim()));$('#results').innerHTML=ps.length?grid(ps):'<div class="panel">Ничего не найдено. Попробуй другое название.</div>';}
function modal(html){$('#detail-body').innerHTML=html;$('#detail').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.fav){fav.has(b.dataset.fav)?fav.delete(b.dataset.fav):fav.add(b.dataset.fav);render()}if(b.dataset.detail){const p=products.find(p=>p.id===b.dataset.detail);modal(`<img src="${p.image}" alt="Иллюстрация категории"><h2>${p.name}</h2><p>${p.text}</p>`)}if(b.dataset.category){category=b.dataset.category;render()}if(b.dataset.devices){devices=Number(b.dataset.devices);render()}if(b.dataset.months){months=Number(b.dataset.months);render()}if(b.hasAttribute('data-vpn'))modal(`<h2>Твой выбор</h2><p>Устройств: ${devices}</p><p>Месяцев: ${months}</p><p class="notice">Это предпросмотр. Цена не установлена, оплата не выполняется.</p>`);if(b.classList.contains('close'))$('#detail').close()});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;results()}if(e.target.id==='theme')document.body.classList.toggle('light',e.target.checked)});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);$('#screen').focus({preventScroll:true})});render();
